In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import VotingRegressor
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv("boston_house_prices.csv",header=1)
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [7]:
df.shape

(506, 14)

In [8]:
X=df.iloc[:,0:13]
y=df.iloc[:,13]

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
477,15.02340,0.0,18.10,0,0.6140,5.304,97.3,2.1007,24,666,20.2,349.48,24.91
15,0.62739,0.0,8.14,0,0.5380,5.834,56.5,4.4986,4,307,21.0,395.62,8.47
332,0.03466,35.0,6.06,0,0.4379,6.031,23.3,6.6407,1,304,16.9,362.25,7.83
423,7.05042,0.0,18.10,0,0.6140,6.103,85.1,2.0218,24,666,20.2,2.52,23.29
19,0.72580,0.0,8.14,0,0.5380,5.727,69.5,3.7965,4,307,21.0,390.95,11.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.17120,0.0,8.56,0,0.5200,5.836,91.9,2.2110,5,384,20.9,395.67,18.66
270,0.29916,20.0,6.96,0,0.4640,5.856,42.1,4.4290,3,223,18.6,388.65,13.00
348,0.01501,80.0,2.01,0,0.4350,6.635,29.7,8.3440,4,280,17.0,390.94,5.99
435,11.16040,0.0,18.10,0,0.7400,6.629,94.6,2.1247,24,666,20.2,109.85,23.27
102,0.22876,0.0,8.56,0,0.5200,6.405,85.4,2.7147,5,384,20.9,70.80,10.63

In [14]:
lr=LinearRegression()
dt=DecisionTreeRegressor()
svr=SVR()

In [16]:
estimators=[('lr',lr),('dt',dt),('svr',svr)]

In [17]:
for estimator in estimators :
    scores=cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
    print(estimator[0],np.round(np.mean(scores),2))

lr 0.2
dt -0.12
svr -0.41

In [18]:
from sklearn.ensemble import VotingRegressor

In [19]:
vr= VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.4

In [21]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vr=VotingRegressor(estimators,weights=[i,j,k])
            scores=cross_val_score(vr,X,y,scoring='r2',cv=10)
            print("For i={},j={},k={}".format(i,j,k),np.round(np.mean(scores),2))

For i=1,j=1,k=1 0.43
For i=1,j=1,k=2 0.36
For i=1,j=1,k=3 0.26
For i=1,j=2,k=1 0.44
For i=1,j=2,k=2 0.38
For i=1,j=2,k=3 0.3
For i=1,j=3,k=1 0.27
For i=1,j=3,k=2 0.39
For i=1,j=3,k=3 0.38
For i=2,j=1,k=1 0.46
For i=2,j=1,k=2 0.41
For i=2,j=1,k=3 0.36
For i=2,j=2,k=1 0.35
For i=2,j=2,k=2 0.39
For i=2,j=2,k=3 0.41
For i=2,j=3,k=1 0.42
For i=2,j=3,k=2 0.45
For i=2,j=3,k=3 0.42
For i=3,j=1,k=1 0.44
For i=3,j=1,k=2 0.44
For i=3,j=1,k=3 0.38
For i=3,j=2,k=1 0.45
For i=3,j=2,k=2 0.47
For i=3,j=2,k=3 0.43
For i=3,j=3,k=1 0.43
For i=3,j=3,k=2 0.46
For i=3,j=3,k=3 0.39

In [22]:
#using same algorithm
dt1=DecisionTreeRegressor(max_depth=1)
dt2=DecisionTreeRegressor(max_depth=3)
dt3=DecisionTreeRegressor(max_depth=5)
dt4=DecisionTreeRegressor(max_depth=7)
dt5=DecisionTreeRegressor(max_depth=None)

In [23]:
estimators=[('dt1',dt1),('dt2',dt2),('dt3',dt3),('dt4',dt4),('dt5',dt5)]

In [24]:
for estimator in estimators:
    scores=cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
    print(estimator[0],np.round(np.mean(scores),2))

dt1 -0.85
dt2 -0.11
dt3 -0.07
dt4 0.1
dt5 -0.16

In [25]:
vr=VotingRegressor(estimators)
scores=cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.18